services:
  ros2:
    image: krushion/blueos-ros2-manta:0.0.1
    container_name: mantaclaus_ros2
    build:
      context: ./
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"

    environment:
      - TERM=xterm-256color
      - XDG_RUNTIME_DIR
      - ROS_DOMAIN_ID=0

    volumes:
      # Map workspace code
      - ./ros2_ws/src/:/root/ros2_ws/src/
      # Persistent workspace for BlueOS
      - ./persistent_ws:/root/persistent_ws
      # PERSIST SSH KEYS: This uses the keys from your Raspberry Pi inside the container
      - /home/pi/.ssh:/root/.ssh

    ports:
      - "4717:4717"
      - "2022:22" # SSH into container via port 2022

    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped


# {
# NetworkMode:"host"
# HostConfig:{
# Binds:[
# 0:"/usr/blueos/extensions/ros2/:/root/persistent_ws/:rw"
# 1:"/dev:/dev:rw"
# 2:"/home/pi/.ssh:/root/.ssh:rw"
# ]
# Privileged:true
# NetworkMode:"host"
# }
# Env:[]
# }